In [17]:
import pandas as pd

data = pd.read_csv('https://raw.githubusercontent.com/npradaschnor/Pima-Indians-Diabetes-Dataset/master/diabetes.csv')

data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [18]:
X = data.drop('Outcome', axis=1)
y = data['Outcome']


In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)


In [20]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)


LogisticRegression(max_iter=1000)

In [21]:
y_scores = model.predict_proba(X_test)[:,1]


In [22]:
y_scores

array([0.04953981, 0.17459294, 0.09362961, 0.25508355, 0.63549111,
       0.11671452, 0.06567364, 0.421926  , 0.04865994, 0.57564702,
       0.3387436 , 0.41301333, 0.69854608, 0.19964664, 0.02001639,
       0.82469745, 0.86657883, 0.03101331, 0.25509887, 0.89492209,
       0.9524559 , 0.8347648 , 0.11741172, 0.44671697, 0.08923667,
       0.06882315, 0.651158  , 0.41198913, 0.1786156 , 0.28690104,
       0.24547132, 0.43901472, 0.00942479, 0.24260196, 0.35170374,
       0.96164437, 0.34358737, 0.80924389, 0.29381458, 0.05083534,
       0.18185267, 0.08672697, 0.42226641, 0.18738662, 0.03011925,
       0.0394947 , 0.24742118, 0.42782612, 0.1052966 , 0.37971089,
       0.99355918, 0.10666912, 0.39100022, 0.76881955, 0.36866773,
       0.45775808, 0.9503522 , 0.4199088 , 0.39154481, 0.0437633 ,
       0.37294413, 0.90128036, 0.88176157, 0.88842796, 0.3308495 ,
       0.06931381, 0.95264287, 0.2005529 , 0.26056043, 0.35463571,
       0.10359498, 0.08168908, 0.45043552, 0.09221286, 0.08648

In [23]:
from sklearn.metrics import roc_curve

fpr, tpr, thresholds = roc_curve(y_test, y_scores)

In [24]:
thresholds

array([       inf, 0.99355918, 0.95264287, 0.9524559 , 0.82469745,
       0.76881955, 0.76200343, 0.68385951, 0.67531274, 0.67422254,
       0.651158  , 0.65085411, 0.63549111, 0.58629047, 0.57564702,
       0.56972966, 0.52515955, 0.4702016 , 0.46129519, 0.45043552,
       0.43901472, 0.43865415, 0.42226641, 0.4199088 , 0.41301333,
       0.41198913, 0.40477451, 0.37971089, 0.36866773, 0.31018821,
       0.30880881, 0.27772611, 0.2720497 , 0.25509887, 0.25508355,
       0.24742118, 0.24547132, 0.23663505, 0.22888031, 0.18185267,
       0.1786156 , 0.17459294, 0.17327014, 0.14637618, 0.14076528,
       0.11671452, 0.11494775, 0.11000816, 0.10666912, 0.08923667,
       0.08672697, 0.02001639, 0.0193133 , 0.00160795])

In [25]:
import plotly.graph_objects as go
import numpy as np


# Generate a trace for ROC curve
trace0 = go.Scatter(
    x=fpr,
    y=tpr,
    mode='lines',
    name='ROC curve'
)

# Only label every nth point to avoid cluttering
n = 10
indices = np.arange(len(thresholds)) % n == 0  # Choose indices where index mod n is 0

trace1 = go.Scatter(
    x=fpr[indices],
    y=tpr[indices],
    mode='markers+text',
    name='Threshold points',
    text=[f"Thr={thr:.2f}" for thr in thresholds[indices]],
    textposition='top center'
)


# Diagonal line
trace2 = go.Scatter(
    x=[0, 1],
    y=[0, 1],
    mode='lines',
    name='Random (Area = 0.5)',
    line=dict(dash='dash')
)

data = [trace0, trace1, trace2]

# Define layout with square aspect ratio
layout = go.Layout(
    title='Receiver Operating Characteristic',
    xaxis=dict(title='False Positive Rate'),
    yaxis=dict(title='True Positive Rate'),
    autosize=False,
    width=800,
    height=800,
    showlegend=False
)

# Define figure and add data
fig = go.Figure(data=data, layout=layout)

# Show figure
fig.show()


In [26]:
# Assume that fpr, tpr, thresholds have already been calculated
optimal_idx = np.argmax(tpr - fpr)
optimal_threshold = thresholds[optimal_idx]
print("Optimal threshold is:", optimal_threshold)


Optimal threshold is: 0.36866773215712084


In [27]:
import plotly.graph_objects as go
import numpy as np
from sklearn.metrics import roc_auc_score

# Assuming fpr, tpr, thresholds are already calculated as before
fpr, tpr, thresholds = roc_curve(y_test, y_scores)

# Calculate the AUC (Area Under the Curve)
roc_auc = roc_auc_score(y_test, y_scores)

# Generate a trace for ROC curve
trace0 = go.Scatter(
    x=fpr,
    y=tpr,
    mode='lines',
    name=f'ROC curve (Area = {roc_auc:.2f})'
)

# Only label every nth point to avoid cluttering
n = 10
indices = np.arange(len(thresholds)) % n == 0  # Choose indices where index mod n is 0

trace1 = go.Scatter(
    x=fpr[indices],
    y=tpr[indices],
    mode='markers+text',
    name='Threshold points',
    text=[f"Thr={thr:.2f}" for thr in thresholds[indices]],
    textposition='top center'
)

# Diagonal line
trace2 = go.Scatter(
    x=[0, 1],
    y=[0, 1],
    mode='lines',
    name='Random (Area = 0.5)',
    line=dict(dash='dash')
)

data = [trace0, trace1, trace2]

# Define layout with square aspect ratio
layout = go.Layout(
    title='Receiver Operating Characteristic',
    xaxis=dict(title='False Positive Rate'),
    yaxis=dict(title='True Positive Rate'),
    autosize=False,
    width=800,
    height=800,
    showlegend=True
)

# Define figure and add data
fig = go.Figure(data=data, layout=layout)

# Show figure
fig.show()


In [28]:
import numpy as np
import plotly.graph_objects as go
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import roc_curve, roc_auc_score
from sklearn.preprocessing import StandardScaler

# Assuming that X_train, X_test, y_train, y_test are already defined

# SVM requires feature scaling for better performance
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Logistic Regression model
lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(X_train, y_train)
lr_scores = lr_model.predict_proba(X_test)[:,1]

# SVM model
svm_model = SVC(probability=True)
svm_model.fit(X_train_scaled, y_train)
svm_scores = svm_model.predict_proba(X_test_scaled)[:,1]

# Generate ROC curve data for logistic regression model
lr_fpr, lr_tpr, lr_thresholds = roc_curve(y_test, lr_scores)
lr_auc = roc_auc_score(y_test, lr_scores)

# Generate ROC curve data for SVM model
svm_fpr, svm_tpr, svm_thresholds = roc_curve(y_test, svm_scores)
svm_auc = roc_auc_score(y_test, svm_scores)

# Generate a trace for the Logistic Regression ROC curve
trace0 = go.Scatter(
    x=lr_fpr,
    y=lr_tpr,
    mode='lines',
    name=f'Logistic Regression (Area = {lr_auc:.2f})'
)

# Generate a trace for the SVM ROC curve
trace1 = go.Scatter(
    x=svm_fpr,
    y=svm_tpr,
    mode='lines',
    name=f'SVM (Area = {svm_auc:.2f})'
)

# Diagonal line
trace2 = go.Scatter(
    x=[0, 1],
    y=[0, 1],
    mode='lines',
    name='Random (Area = 0.5)',
    line=dict(dash='dash')
)

data = [trace0, trace1, trace2]

# Define layout with square aspect ratio
layout = go.Layout(
    title='Receiver Operating Characteristic',
    xaxis=dict(title='False Positive Rate'),
    yaxis=dict(title='True Positive Rate'),
    autosize=False,
    width=800,
    height=800,
    showlegend=True
)

# Define figure and add data
fig = go.Figure(data=data, layout=layout)

# Show figure
fig.show()


In [30]:
lr_auc

0.7934760448521917

In [31]:
svm_auc

0.8120285423037716

In [41]:
a=pd.DataFrame(roc_curve(y_test, y_scores))
at= a.T
at.columns= ('fpr', 'tpr', 'thresholds')
at

fpr       tpr  thresholds
0   0.000000  0.000000         inf
1   0.000000  0.022222    0.993559
2   0.000000  0.088889    0.952643
3   0.009174  0.088889    0.952456
4   0.009174  0.288889    0.824697
5   0.027523  0.288889    0.768820
6   0.027523  0.311111    0.762003
7   0.073394  0.311111    0.683860
8   0.073394  0.333333    0.675313
9   0.082569  0.333333    0.674223
10  0.082569  0.377778    0.651158
11  0.091743  0.377778    0.650854
12  0.091743  0.400000    0.635491
13  0.100917  0.400000    0.586290
14  0.100917  0.444444    0.575647
15  0.110092  0.444444    0.569730
16  0.110092  0.488889    0.525160
17  0.128440  0.488889    0.470202
18  0.128440  0.533333    0.461295
19  0.146789  0.533333    0.450436
20  0.146789  0.577778    0.439015
21  0.155963  0.577778    0.438654
22  0.155963  0.622222    0.422266
23  0.174312  0.622222    0.419909
24  0.174312  0.644444    0.413013
25  0.183486  0.644444    0.411989
26  0.183486  0.666667    0.404775
27  0.220183  0.666667    0.379711
28  0.220183  0.733333    0.368668
29  0.302752  0.733333    0.310188
30  0.302752  0.755556    0.308809
31  0.357798  0.755556    0.277726
32  0.357798  0.777778    0.272050
33  0.394495  0.777778    0.255099
34  0.394495  0.800000    0.255084
35  0.403670  0.800000    0.247421
36  0.403670  0.822222    0.245471
37  0.422018  0.822222    0.236635
38  0.422018  0.844444    0.228880
39  0.532110  0.844444    0.181853
40  0.532110  0.866667    0.178616
41  0.541284  0.866667    0.174593
42  0.541284  0.888889    0.173270
43  0.577982  0.888889    0.146376
44  0.577982  0.911111    0.140765
45  0.633028  0.911111    0.116715
46  0.633028  0.933333    0.114948
47  0.660550  0.933333    0.110008
48  0.660550  0.955556    0.106669
49  0.743119  0.955556    0.089237
50  0.743119  0.977778    0.086727
51  0.981651  0.977778    0.020016
52  0.981651  1.000000    0.019313
53  1.000000  1.000000    0.001608

In [43]:
(lr_scores >= 0.5).astype(int)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0])