In [1]:
import pandas as pd

# Load your CSV file
df = pd.read_csv("PV Classification.csv")
df

ID  Seriousness                                          Narrative
0      1  Non-serious  Two hours after taking a new antihistamine for...
1      2         D/LT  Within an hour of receiving a new chemotherapy...
2      3  Non-serious  On day three of a new antibiotic for a sinus i...
3      4      Serious  Five days after starting a new anticoagulant, ...
4      5  Non-serious  After my flu shot, I developed a low-grade fev...
..   ...          ...                                                ...
645  646  Non-serious  My child developed mild diarrhea after receivi...
646  647      Serious  After administration of a long-acting injectab...
647  648         D/LT  Patient with chronic kidney disease received g...
648  649  Non-serious  Applying a eucalyptus balm caused a temporary ...
649  650      Serious  I started on isoniazid for latent TB and devel...

[650 rows x 3 columns]

In [2]:
# Only keep the text and labels
texts = df["Narrative"].tolist()
labels = df["Seriousness"].tolist()

In [3]:
texts

['Two hours after taking a new antihistamine for seasonal allergies, I developed a mild headache and slight fatigue. The headache was a dull pressure in my forehead, and the fatigue made me feel slightly sluggish. I drank water, avoided screen time, and rested for a few hours. By evening, both symptoms resolved. My doctor said these were common initial side effects, and they didn’t recur with subsequent doses.',
 'Within an hour of receiving a new chemotherapy infusion, I experienced severe chest pain, difficulty breathing, and a rapid heartbeat. I felt faint and clammy, and the infusion was stopped immediately. Paramedics rushed me to the ER, where I was diagnosed with an anaphylactic reaction. I received emergency treatment with epinephrine and steroids, and was admitted to the ICU for 48 hours. The drug was discontinued, and my treatment plan was revised.',
 'On day three of a new antibiotic for a sinus infection, I noticed mild nausea and occasional stomach cramps. The symptoms beg

In [4]:
labels

['Non-serious',
 'D/LT',
 'Non-serious',
 'Serious',
 'Non-serious',
 'D/LT',
 'Non-serious',
 'Serious',
 'Non-serious',
 'D/LT',
 'Non-serious',
 'Serious',
 'Non-serious',
 'D/LT',
 'Non-serious',
 'Serious',
 'Non-serious',
 'D/LT',
 'Non-serious',
 'Serious',
 'Non-serious',
 'D/LT',
 'Non-serious',
 'Serious',
 'Non-serious',
 'D/LT',
 'Non-serious',
 'Serious',
 'Non-serious',
 'D/LT',
 'Non-serious',
 'Serious',
 'Non-serious',
 'D/LT',
 'Non-serious',
 'Serious',
 'Non-serious',
 'D/LT',
 'Non-serious',
 'Serious',
 'Non-serious',
 'D/LT',
 'Non-serious',
 'Serious',
 'Non-serious',
 'D/LT',
 'Non-serious',
 'Serious',
 'Non-serious',
 'D/LT',
 'Non-serious',
 'D/LT',
 'Non-serious',
 'Serious',
 'Non-serious',
 'D/LT',
 'Non-serious',
 'Serious',
 'Non-serious',
 'D/LT',
 'Non-serious',
 'Serious',
 'Non-serious',
 'D/LT',
 'Non-serious',
 'Serious',
 'Non-serious',
 'D/LT',
 'Non-serious',
 'Serious',
 'Non-serious',
 'D/LT',
 'Non-serious',
 'Serious',
 'Non-serious',
 'D/L

## 🏷️ Convert Labels to Numbers

In [5]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
labels_encoded = label_encoder.fit_transform(labels)

In [6]:
labels_encoded

array([1, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1, 2, 1, 0,
       1, 2, 1, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1, 2,
       1, 0, 1, 2, 1, 0, 1, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1, 2,
       1, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1, 2, 1, 0,
       1, 2, 1, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1, 0, 1, 2, 1, 0, 1, 2, 1, 0,
       1, 2, 1, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1, 2,
       1, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1, 0, 1, 2,
       1, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1, 2, 1, 0,
       1, 2, 1, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1, 2,
       1, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2,
       0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
       1, 2, 0, 1, 2, 0, 1, 2, 1, 0, 2, 1, 0, 2, 1, 0, 2, 1, 0, 2, 1, 0,
       2, 0, 1, 2, 2, 1, 0, 2, 1, 2, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 2, 0,
       1, 2, 1, 2, 0, 2, 1, 2, 0, 2, 1, 0, 2, 1, 2,

## 🤖 Load BioBERT Tokenizer

In [7]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("dmis-lab/biobert-base-cased-v1.1", cache_dir="hf_models")


c:\Users\Jeevan\miniconda3\envs\bert_env\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\Users\Jeevan\miniconda3\envs\bert_env\lib\site-packages\huggingface_hub\file_download.py:945: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


## 🧹 Tokenize Text

In [8]:
# Convert text to input IDs and attention masks
encodings = tokenizer(texts, truncation=True, padding=True, max_length=256, return_tensors="tf")

In [9]:
encodings

{'input_ids': <tf.Tensor: shape=(650, 103), dtype=int32, numpy=
array([[  101,  1160,  2005, ...,     0,     0,     0],
       [  101,  1439,  1126, ...,  8182,   119,   102],
       [  101,  1113,  1285, ...,     0,     0,     0],
       ...,
       [  101,  5351,  1114, ...,     0,     0,     0],
       [  101, 11892,   170, ...,     0,     0,     0],
       [  101,   178,  1408, ...,     0,     0,     0]])>, 'token_type_ids': <tf.Tensor: shape=(650, 103), dtype=int32, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])>, 'attention_mask': <tf.Tensor: shape=(650, 103), dtype=int32, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]])>}

## 📊 Prepare Dataset for Training

In [10]:
import tensorflow as tf
from tensorflow.data import Dataset

dataset = Dataset.from_tensor_slices(
    (dict(encodings), labels_encoded)
)

In [11]:
int(0.8 * len(dataset))

520

In [12]:
train_size = int(0.8 * len(dataset))
train_dataset = dataset.take(train_size).shuffle(100).batch(8)
val_dataset = dataset.skip(train_size).batch(8)

## 🧠 Load BioBERT Model for Classification

In [13]:
from transformers import TFAutoModelForSequenceClassification

# Load the PyTorch weights and convert them to TensorFlow
model = TFAutoModelForSequenceClassification.from_pretrained(
    "dmis-lab/biobert-base-cased-v1.1",
    num_labels=3,
    from_pt=True,  # This tells it to load from PyTorch weights
    cache_dir="hf_models"
)


All PyTorch model weights were used when initializing TFBertForSequenceClassification.

Some weights or buffers of the TF 2.0 model TFBertForSequenceClassification were not initialized from the PyTorch model and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


## ⚙️ Compile the Model

In [14]:
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import SparseCategoricalCrossentropy

optimizer = Adam(learning_rate=5e-5)
loss = SparseCategoricalCrossentropy(from_logits=True)

model.compile(optimizer=optimizer, loss=loss, metrics=["accuracy"])

## 🚀 Train the Model

In [ ]:
# model.fit(
#     train_dataset,
#     validation_data=val_dataset,
#     epochs=5
# )

Epoch 1/5


65/65 [==============================] - 181s 2s/step - loss: 0.5529 - accuracy: 0.7596 - val_loss: 0.3012 - val_accuracy: 0.8538
Epoch 2/5
65/65 [==============================] - 152s 2s/step - loss: 0.2486 - accuracy: 0.9077 - val_loss: 0.5364 - val_accuracy: 0.8308
Epoch 3/5
65/65 [==============================] - 155s 2s/step - loss: 0.0893 - accuracy: 0.9673 - val_loss: 0.3624 - val_accuracy: 0.8923
Epoch 4/5
65/65 [==============================] - 155s 2s/step - loss: 0.0448 - accuracy: 0.9904 - val_loss: 0.5139 - val_accuracy: 0.8538
Epoch 5/5
65/65 [==============================] - 151s 2s/step - loss: 0.0400 - accuracy: 0.9827 - val_loss: 0.2268 - val_accuracy: 0.9308


In [16]:
model.save_pretrained("./hf_models/biobert_seriousness_model")
tokenizer.save_pretrained("./hf_models/biobert_seriousness_model")

('./hf_models/biobert_seriousness_model\\tokenizer_config.json',
 './hf_models/biobert_seriousness_model\\special_tokens_map.json',
 './hf_models/biobert_seriousness_model\\vocab.txt',
 './hf_models/biobert_seriousness_model\\added_tokens.json',
 './hf_models/biobert_seriousness_model\\tokenizer.json')

In [21]:
#OR

model.save("biobert_seriousness_model")

INFO:tensorflow:Assets written to: biobert_seriousness_model\assets


INFO:tensorflow:Assets written to: biobert_seriousness_model\assets


## ✅ Load the Saved Model

In [1]:
from transformers import TFBertForSequenceClassification, BertTokenizer

# Load from the directory you saved to
model = TFBertForSequenceClassification.from_pretrained("./hf_models/biobert_seriousness_model")
tokenizer = BertTokenizer.from_pretrained("./hf_models/biobert_seriousness_model")

c:\Users\Jeevan\miniconda3\envs\bert_env\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


All model checkpoint layers were used when initializing TFBertForSequenceClassification.

All the layers of TFBertForSequenceClassification were initialized from the model checkpoint at ./hf_models/biobert_seriousness_model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForSequenceClassification for predictions without further training.


In [3]:
import tensorflow as tf

def predict_seriousness(text):
    # Tokenize text
    inputs = tokenizer(text, return_tensors="tf", truncation=True, max_length=128)
    
    # Get model predictions
    outputs = model(**inputs)
    
    # Convert logits to probabilities (for all 3 classes)
    proba = tf.nn.softmax(outputs.logits, axis=1).numpy()[0]
    
    # Get predicted class (0, 1, or 2)
    predicted_class = tf.argmax(proba).numpy()
    
    # Map to label names
    label_names = ["DLT", "Non-serious", "Serious"]  # Must match your training labels
    return label_names[predicted_class], proba, predicted_class

# Example usage
text = "Patient experienced severe vomiting and required hospitalization"
label, confidence_scores, predicted_class = predict_seriousness(text)
print(f"Predicted: {label} | Confidence: {confidence_scores[predicted_class]:.2f}")

Predicted: Serious | Confidence: 0.97


In [ ]:
import tensorflow as tf

def predict_seriousness(text):
    # Tokenize text
    inputs = tokenizer(text, return_tensors="tf", truncation=True, max_length=128)
    
    # Get model predictions
    outputs = model(**inputs)
    
    # Convert logits to probabilities (for all 3 classes)
    proba = tf.nn.softmax(outputs.logits).numpy()[0]
    
    # Get predicted class (0, 1, or 2)
    predicted_class = tf.argmax(proba).numpy()
    
    # Map to label names
    label_names = ["DLT", "Non-serious", "Serious"]  # Must match your training labels
    return label_names[predicted_class], "Confidence:", proba[predicted_class]

In [14]:
predict_seriousness("patient died")

('DLT', 'Confidence: ', 0.87825364)

In [16]:
text ="Two weeks after starting a new heart medication, I experienced severe fatigue and fainting spells. I was admitted for suspected arrhythmia. The drug was stopped, and I received a pacemaker. I stabilized after five days."

In [17]:
inputs = tokenizer(text, return_tensors="tf", truncation=True, max_length=128)
input

<bound method Kernel.raw_input of <ipykernel.ipkernel.IPythonKernel object at 0x00000229F684E050>>

In [19]:
outputs= model(**inputs)
outputs

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-0.9634368, -2.6876621,  3.7950063]], dtype=float32)>, hidden_states=None, attentions=None)

In [28]:
tf.nn.softmax(outputs.logits).numpy()

array([[0.0084931 , 0.00151441, 0.98999244]], dtype=float32)

## Test on unseen data

In [38]:
import pandas as pd

# Load your test CSV (same format as training data)
test_df = pd.read_csv("test.csv")  # Columns: ID, Seriousness, Narrative

test_df.head()

ID  Seriousness                                          Narrative
0  651  Non-serious  After applying a topical gel for muscle sorene...
1  652      Serious  Two weeks after starting lithium for mood stab...
2  653         D/LT  Shortly after receiving a chemotherapy cycle, ...
3  654  Non-serious  I took a multivitamin with iron and noticed a ...
4  655      Serious  A week after starting carbamazepine, I develop...

In [69]:
import tensorflow as tf
from transformers import TFBertForSequenceClassification, BertTokenizerFast


model = TFBertForSequenceClassification.from_pretrained("./hf_models/biobert_seriousness_model")
tokenizer = BertTokenizer.from_pretrained("./hf_models/biobert_seriousness_model")
encodings = tokenizer(texts, truncation=True, padding=True, max_length=256, return_tensors="tf")

Some layers from the model checkpoint at ./hf_models/biobert_seriousness_model were not used when initializing TFBertForSequenceClassification: ['dropout_37']
- This IS expected if you are initializing TFBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertForSequenceClassification were initialized from the model checkpoint at ./hf_models/biobert_seriousness_model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForSequenceClassification for predictions without further training.


In [70]:
texts = test_df["Narrative"].tolist()
labels = test_df["Seriousness"].tolist()

In [71]:
label_encoder = LabelEncoder()
labels_encoded = label_encoder.fit_transform(labels)

In [72]:
test_dataset = tf.data.Dataset.from_tensor_slices((dict(encodings), labels_encoded)).batch(16)

In [73]:
# Compile the model for evaluation
from tensorflow.keras.losses import SparseCategoricalCrossentropy
from tensorflow.keras.optimizers import Adam

model.compile(
    optimizer=Adam(learning_rate=5e-5),
    loss=SparseCategoricalCrossentropy(from_logits=True),
    metrics=["accuracy"]
)

# Evaluate
loss, accuracy = model.evaluate(test_dataset)
print(f"Test Loss: {loss:.4f}, Test Accuracy: {accuracy:.4f}")

4/4 [==============================] - 7s 371ms/step - loss: 0.3199 - accuracy: 0.9200
Test Loss: 0.3199, Test Accuracy: 0.9200


In [74]:
from sklearn.metrics import classification_report, confusion_matrix

# Get predictions
y_pred_logits = model.predict(test_dataset).logits
y_pred = tf.argmax(y_pred_logits, axis=1).numpy()

# Decode labels (optional)
y_true = labels_encoded

print("Classification Report:\n", classification_report(y_true, y_pred))


4/4 [==============================] - 5s 379ms/step
Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.94      0.88        16
           1       1.00      1.00      1.00        17
           2       0.93      0.82      0.88        17

    accuracy                           0.92        50
   macro avg       0.92      0.92      0.92        50
weighted avg       0.92      0.92      0.92        50



In [75]:
label_names = ["DLT", "Non-serious", "Serious"]  